on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: x86_64-unknown-linux-gnu
          args: "--locked --release"
          strip: true
      - name: Compress public dir
        run: tar -czf public.tar.gz web-server/public
      - name: Compress binary
        run: tar -czf binary.tar.gz ./target/x86_64-unknown-linux-gnu/release/web-server
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          source: "binary.tar.gz,public.tar.gz"
          target: /app
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          script: |
            cd /app
            tar -xzf *.tar.gz
            killall web-server
            ./web-server &
