on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          SRC_DIR: ./web-server
          UPLOAD_MODE: none
          TOOLCHAIN_VERSION: stable
          RUSTTARGET: x86_64-unknown-linux-musl
          ARCHIVE_TYPES: tar.gz
          EXTRA_FILES: ./web-server/public/
#      - uses: actions/checkout@master
#      - name: Compress public dir
#        run: tar -czf public.tar.gz web-server/public
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          source: "public.tar.gz,${{ steps.compile.outputs.BUILT_ARCHIVE }}"
          target: /app
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          script: |
            cd /app
            tar -xzf *.tar.gz
            rm *.tar.gz
            killall rustcwb
            ./rustcwb &