on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: x86_64-unknown-linux-gnu
          args: "--locked --release --bin web-server"
          strip: true
      - name: minifycss
        uses: nizarmah/auto-minify@v3
        with:
          js_engine: uglify-js
          css_engine: lightning
          directory: ./web-server/public/assets/css
          overwrite: true
      - name: Archive npm failure logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs
      - name: Compress public dir
        run: tar -czf public.tar.gz -C web-server public/
      - name: Compress binary
        run: tar -czf binary.tar.gz -C ./target/x86_64-unknown-linux-gnu/release web-server
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          source: "binary.tar.gz,public.tar.gz,deploy/deploy.sh"
          target: /app
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          script: |
            /app/deploy/deploy.sh
